language: cpp

install: cmake

os: windows

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

before_install:
    - eval "${MATRIX_EVAL}"

compiler:
  - gcc
  - clang

before_script:
  # Create a build directory (out of source).
  - cmake -E make_directory build
  # Generate project files.
  - cmake -E chdir build cmake ..

script:
  # Build the out of source project files.
  - cmake --build build
  # Run regression tests via ctest.
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake -E chdir build ctest -C Debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -E chdir build ctest; fi